import { createContext, useContext, useEffect, useState } from "react";

type Language = "en" | "th";

type LanguageProviderProps = {
  children: React.ReactNode;
  defaultLanguage?: Language;
};

type LanguageProviderState = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
};

const LanguageProviderContext = createContext<
  LanguageProviderState | undefined
>(undefined);

// Simple translation dictionary
const translations: Record<Language, Record<string, string>> = {
  en: {
    "app.title": "Ban Phuttachad Dormitory",
    "nav.dashboard": "Dashboard",
    "nav.rooms": "Rooms",
    "nav.tenants": "Tenants",
    "nav.tenantsold": "Tenant history",
    "nav.staff": "Staff",
    "nav.billing": "Billing",
    "nav.repairs": "Repairs",
    "nav.announcements": "Announcements",
    "nav.reports": "Reports",
    "nav.profile": "Profile",
    "nav.settings": "Settings",
    "auth.login": "Login",
    "auth.logout": "Logout",
    "auth.register": "Register",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.confirmPassword": "Confirm Password",
    "auth.role": "Role",
    "auth.welcomeBack": "Welcome back",
    "auth.pleaseLogin": "Please login to continue",
    "dashboard.welcome": "Welcome to your Dashboard",
    "dashboard.summary": "Here's a summary of your dormitory",
    "dashboard.totalRooms": "Total Rooms",
    "dashboard.occupiedRooms": "Occupied",
    "dashboard.vacantRooms": "Vacant",
    "dashboard.pendingRepairs": "Pending Repairs",
    "dashboard.monthlyRevenue": "Monthly Revenue",
    "dashboard.revenueTrend": "Revenue trend over the last 6 months",
    "dashboard.revenue": "Revenue",
    "dashboard.roomStatus": "Room Status",
    "dashboard.currentRoomOccupancy": "Current room occupancy",
    "dashboard.roomsOccupied": "Rooms Occupied",
    "dashboard.occupancy": "Occupancy",
    "dashboard.Description": "Revenue trend over the last 6 months",
    "rooms.management": "Room Management",
    "rooms.allTypes": "All Types",
    "rooms.number": "Room Number",
    "rooms.type": "Room Type",
    "rooms.status": "Status",
    "rooms.rent": "Monthly Rent",
    "rooms.size": "Room Size",
    "rooms.capacity": "Capacity",
    "rooms.floor": "Floor",
    "rooms.add": "Add Room",
    "rooms.addDesc": "Add a new room to the dormitory.",
    "Standard.Single": "Standard Single",
    "Standard.Double": "Standard Double",
    "satatus.occupied": "Occupied",
    "satatus.vacant": "Vacant",
    "satatus.maintenance": "Maintenance",
    "status.text": "Room Status",
    "rooms.edit": "Edit Room",
    "rooms.delete": "Delete Room",
    "tenants.management": "Tenant Management",
    "tenants.name": "Name",
    "tenants.room": "Room",
    "tenants.contactInfo": "Contact Info",
    "tenants.leaseStart": "Lease Start",
    "tenants.leaseEnd": "Lease End",
    "tenants.add": "Add Tenant",
    "tenants.edit": "Edit Tenant",
    "tenants.delete": "Delete Tenant",
    "repairs.management": "Repair Management",
    "repairs.room": "Room",
    "repairs.status": "Status",
    "repairs.date": "Date Reported",
    "repairs.add": "Add Repair Request",
    "repairs.edit": "Edit Repair",
    "repairs.delete": "Delete Repair",
    "repairs.viewDetails": "Repair Details",
    "repairs.roomNumber": "Room",
    "repairs.description": "Description",
    "repairs.reportedDate": "Reported Date",
    "repairs.completedDate": "Completed Date",
    "repairs.status.pending": "Pending",
    "repairs.status.in_progress": "In Progress",
    "repairs.status.completed": "Completed",
    "repairs.status.cancelled": "Cancelled",
    "language.en": "English",
    "language.th": "ไทย",
    "theme.title": "Theme & Language",
    "theme.description": "Customize the appearance and language of the system.",
    "theme.theme": "Theme",
    "theme.light": "Light",
    "theme.dark": "Dark",
    "theme.language": "Language",
    "theme.thai": "Thai",
    "theme.english": "English",
    "theme.lightTheme": "Light Theme",
    "theme.darkTheme": "Dark Theme",
    "roomer.text1": "Room Status",
    "roomer.text2": "Current room occupancy",
    "footer.rights": "All rights reserved",
    "welcome.title": "Welcome to Ban Phuttachad, Nakhon Pathom",
    "welcome.subtitle": "Modern living spaces for students",
    "welcome.login": "Login ",
    "welcome.explore": "Rooms Detils",
    "welcome.features": "Our Features",
    "welcome.location": "Prime Location",
    "welcome.security": "24h Security",
    "welcome.amenities": "Modern Amenities",
    "welcome.contact": "Contact Us",
    "profile.title": "Profile",
    "profile.manage": "Manage your personal information",
    "profile.firstName": "First Name",
    "profile.lastName": "Last Name",
    "profile.email": "Email",
    "profile.phone": "Phone Number",
    "profile.address": "Address",
    "profile.enterPhone": "Enter your phone number",
    "profile.enterAddress": "Enter your address",
    "profile.save": "Save Changes",
    "profile.saving": "Saving...",
    "profile.saveSuccess": "Profile saved successfully!",
    "profile.saveError": "Could not save profile",
    "profile.userNotFound": "User not found",
    "profile.genericError": "An error occurred while saving",
    "system.title": "System Settings",
    "system.description": "System configuration and maintenance (admin only)",
    "system.info": "System Information",
    "system.totalRooms": "Total Rooms",
    "system.occupiedRooms": "Occupied Rooms",
    "system.totalTenants": "Total Tenants",
    "system.pendingRepairs": "Pending Repairs",
    "system.configTitle": "System Configuration",
    "system.waterRate": "Water Rate (per person/baht)",
    "system.electricityRate": "Electricity Rate (baht/unit)",
    "system.lateFee": "Late Payment Fee (%)",
    "All Statuses": "All Statuses",
    "system.depositRate": "Monthly Rent",
    "system.floor": "Building Floor",
    "system.save": "Save Settings",
    "system.saving": "Saving...",
    "system.maintenance": "System Maintenance",
    "system.backup": "Backup Data",
    "system.backuping": "Backing up...",
    "system.clearCache": "Clear Cache",
    "system.check": "System Check",
    "system.status": "System Status",
    "system.database": "Database",
    "system.connection": "Connection",
    "system.storage": "Storage",
    "system.normal": "Normal",
    "system.used": "Used 65%",
    "reports.title": "Reports",
    "reports.subtitle": "View and analyze dormitory data",
    "reports.exportPdf": "Export PDF",
    "reports.exporting": "Exporting...",
    "reports.options": "Report Options",
    "reports.selectType": "Select the report type",
    "reports.type": "Report Type",
    "reports.selectTypePlaceholder": "Select report type",
    "reports.selectTypeDesc": "Select a report type to view data",
    "reports.occupancyTitle": "Occupancy Trends",
    "reports.occupancyDesc": "Monthly dormitory occupancy rates",
    "reports.revenueTitle": "Revenue Analysis",
    "reports.revenueDesc": "Monthly revenue breakdown",
    "reports.roomTypeTitle": "Room Type Distribution",
    "reports.roomTypeDesc": "Distribution of different room types",
    "reports.repairTitle": "Repair Request Analysis",
    "reports.repairDesc": "Types of repair requests received",
    "reports.eventTitle": "Event Attendance",
    "reports.eventDesc": "Dormitory event participation metrics",
    "loading": "Loading...",
    "rooms.details": "Room",
    "rooms.detailsDesc": "All information about this room",
    "rooms.person": "person",
    "rooms.currentTenants": "Current Tenants",
    "rooms.mainTenant": "Main Tenant",
    "rooms.subTenant": "Sub Tenant",
    "rooms.noCurrentTenant": "No current tenants",
    "rooms.detailsTitle": "Rooms Details",
    "loadingTenants": "Loading tenants...",
    "manageSystemUsers": "Manage System Users",
    "tenants.managementDesc": "Manage tenant information and rented rooms in the apartment.",
    "tenants.searchTitle": "Search Tenants",
    "Search by room number": "Search by room number",
    "tenants.searchDesc": "Search tenants by name, email, phone, or room number.",
    "tenants.searchPlaceholder": "Search tenants...",
    "tenants.listTitle": "Tenant List",
    "tenants.showCount": "Showing Tenants",
    "tenants.phone": "Phone",
    "tenants.address": "Address",
    "tenants.createdAt": "Date Added",
    "tenants.noData": "No tenant data",
    "tenants.main": "Main Tenant",
    "tenants.child": "Sub Tenant",
    "tenants.notRented": "Not rented",
    "tenants.addChild": "Add Sub Tenant",
    "tenants.viewContractImage": "View Contract Image",
    "tenants.addContractImage": "Add Contract Image",
    "tenants.deleteChild": "Delete Sub Tenant",
    "tenants.deleteConfirm": "Are you sure you want to delete ?",
    "tenants.deleteChildConfirm": "Are you sure you want to delete the sub tenant of ?",
    "tenants.deleteSuccess": "Tenant deleted successfully",
    "tenants.formDesc": "Please fill in all tenant information.",
    "tenants.firstNameRequired": "Please enter first name",
    "tenants.lastNameRequired": "Please enter last name",
    "tenants.emailInvalid": "Invalid email address",
    "tenants.phoneRequired": "Please enter phone number",
    "tenants.houseNumberRequired": "Please enter house number",
    "tenants.villageRequired": "Please enter village",
    "tenants.subDistrictRequired": "Please enter sub-district",
    "tenants.districtRequired": "Please enter district",
    "tenants.provinceRequired": "Please enter province",
    "dashboard.totalRevenue": "Total Revenue",
    "dashboard.Revenue": "Revenue",
    "tenants.tenantInfo": "Tenant Information",
    "tenants.residents": "Residents",
    "tenants.selectDistrictFirst": "Please select district first",
    "tenants.saveTenant": "Save Tenant",
    "tenants.saveResident": "Save Resident",
    "tenants.checkIn": "Check In",
    "tenants.lastUpdated": "Last Updated",
    "tenants.floor": "Floor",
    "tenants.emergencyContact": "Emergency Contact",
    "tenants.roommates": "Roommates",
    "tenants.viewContractFile": "View Contract File",
    "tenants.showContractFileDesc": "Display the tenant's contract file",
    "tenants.loadingFile": "Loading file...",
    "tenants.fileNotFound": "Contract file not found",
    "tenants.pdfContractTitle": "PDF Contract",
    "tenants.contractImageAlt": "Contract",
    "profile.tenantOnlyEdit": "Only tenants can edit their own profile",
    "announcements.calendar": "Calendar",
    "announcements.add": "Add Announcement",
    "announcements.edit": "Edit Announcement",
    "announcements.delete": "Delete Announcement",
    "announcements.title": "Title",
    "announcements.description": "Description",
    "announcements.date": "Date",
    "announcements.time": "Time",
    "announcements.addSuccess": "Announcement added successfully",
    "announcements.editSuccess": "Announcement updated successfully",
    "announcements.deleteSuccess": "Announcement deleted successfully",
    "announcements.deleteConfirm": "Are you sure you want to delete this announcement?",
    "announcements.deleteError": "Failed to delete announcement. Please try again.",
    "announcements.addError": "Failed to add announcement. Please try again.",
    "announcements.editError": "Failed to update announcement. Please try again.",
    "announcements.noAnnouncements": "No announcements available",
    "announcements.noData": "No announcement data",
    "announcements.viewDetails": "View Details",
    "announcements.editDetails": "Edit Announcement Details",
    "announcements.deleteDetails": "Delete Announcement Details",
    "announcements.loading": "Loading announcements...",
    "announcements.loadingError": "Failed to load announcements. Please try again.",
    "announcements.calendarView": "Calendar View",
    "announcements.listView": "List View",
    "announcements.view": "View Announcement",
    "announcements.viewDesc": "View the details of this announcement",
    "announcements.addDesc": "Add a new announcement for tenants",
    "announcements.editDesc": "Edit the selected announcement",
    "announcements.deleteDesc": "Delete the selected announcement",
    "announcements.titleRequired": "Announcement title is required",
    "announcements.descriptionRequired": "Announcement description is required",
    "announcements.dateRequired": "Announcement date is required",
    "announcements.timeRequired": "Announcement time is required",
    "announcements.titlePlaceholder": "Enter announcement title",
    "announcements.descriptionPlaceholder": "Enter announcement description",
    "announcements.datePlaceholder": "Select announcement date",
    "announcements.timePlaceholder": "Select announcement time",
    "announcements.addAnnouncement": "Add Announcement",
    "announcements.editAnnouncement": "Edit Announcement",
    "announcements.deleteAnnouncement": "Delete Announcement",
    "announcements.viewAnnouncement": "View Announcement",
    "announcements.announcementDetails": "Announcement Details",
    "announcements.announcementList": "Announcement List",
    "announcements.recent": "Recent Announcements",
    "days.Sun": "Sunday",
    "days.Mon": "Monday",
    "days.Tue": "Tuesday",
    "days.Wed": "Wednesday",
    "days.Thu": "Thursday",
    "days.Fri": "Friday",
    "days.Sat": "Saturday",
    "announcements.forDate": "For Date",
    "announcements.noForDate": "No announcements for this date",
    "announcements.noAvailable": "No announcements available for this date",
    "announcements.createDescription": "Create a new announcement for tenants",
    "announcements.markImportant": "Mark as Important",
    "announcements.contentPlaceholder": "Enter announcement content here",
    "repairs.title": "Repairs",
    "repairs.subtitle": "Manage repair requests and maintenance",
    "repairs.searchPlaceholder": "Search repairs",
    "repairs.descriptionPlaceholder": "Enter repair description here",
    "repairs.status_pending": "Pending",
    "repairs.status_in_progress": "In Progress",
    "repairs.status_completed": "Completed",
    "repairs.status_cancelled": "Cancelled",
    "repairs.createDescription": "Create a new repair request for tenants",
    "repairs.status_all": "All Statuses",
    "common.actions": "Actions",
    "common.delete": "Delete",
    "common.viewDetails": "View",
    "common.edit": "Edit",
    "repairs.markInProgress": "Mark as Important",
    "repairs.markImportant": "Mark as Important",
    "repairs.markCompleted": "Mark as Completed",
    "repairs.markCancelled": "Mark as Cancelled",
    "repairs.selectRoom": "Select Room",
    "Actions.text": "Actions",
    "view_details": "View Details",
    "edit": "Edit",
    "calendar.infoTitle": "Calendar Information",
    "calendar.infoDesc": "View and manage events on the calendar",
    "calendar.title": "Calendar",
    "calendar.subtitle": "Manage your events and announcements",
    "welcome.phone": "Phone",
    "welcome.facebook": "Facebook",
    "dashboard.overview": "Overview of the Dormitory Management System",
    "billing.title": "Billing System",
    "billing.description": "Manage dormitory billing and expenses",
    "billing.export": "Export",
    "billing.calculate": "Calculate Expenses",
    "billing.filtersTitle": "Search & Filter",
    "billing.filtersDesc": "Search bills by tenant name or room number and filter by month/year",
    "billing.searchPlaceholder": "Search bills...",
    "billing.statusFilter": "Filter by status",
    "billing.status_all": "All statuses",
    "billing.status_paid": "Paid",
    "billing.status_pending": "Pending",
    "billing.status_overdue": "Overdue",
    "billing.listTitle": "Billing List",
    "billing.showCount": "Showing",
    "billing.month": "Month",
    "billing.receiptNumber": "Receipt Number",
    "billing.tenant": "Tenant",
    "billing.room": "Room",
    "billing.roomRent": "Room Rent",
    "billing.waterCost": "Water",
    "billing.electricityCost": "Electricity",
    "billing.total": "Total",
    "billing.dueDate": "Due Date",
    "billing.status": "Status",
    "billing.paidDate": "Paid Date",
    "billing.actions": "Actions",
    "billing.personUnit": "person(s)",
    "billing.electricityUnit": "unit(s)",
    "billing.viewDetails": "View Details",
    "billing.edit": "Edit",
    "billing.markAsPaid": "Mark as Paid",
    "billing.pay": "Pay",
    "billing.noData": "No billing data found",
    "billing.confirmMarkAsPaid": "Are you sure you want to confirm payment?",
    "billing.cancel": "Cancel",
    "billing.confirm": "Confirm Payment",
    "billing.calculateTitle": "Calculate Expenses (by room)",
    "billing.calculateDesc": "Calculate rent + water + electricity",
    "billing.createBill": "Create Bill",
    "billing.creating": "Creating...",
    "common.cancel": "Cancel",
    "billing.billingDate": "Billing Date",
    "billing.detailTitle": "Bill Details",
    "billing.forRoom": "Bill for room",
    "billing.printReceipt": "Print Receipt",
    "billing.tenantInfo": "Tenant Information",
    "billing.roomNumber": "Room Number",
    "billing.tenantName": "Tenant Name",
    "billing.expenseDetail": "Expense Details",
    "billing.forMonth": "For {month}",
    "billing.baht": "baht",
    "billing.paymentInfo": "Payment Information",
    "billing.notPaid": "Not paid yet",
    "billing.createdAt": "Bill Created At",
    "billing.paymentSuccess": "Payment Successful",
    "billing.paymentSuccessDesc": "Your payment has been completed.",
    "billing.previousMeter": "Previous Meter",
    "billing.currentMeter": "Current Meter",
    "billing.meterError": "Please enter a valid current meter reading.",
    "billing.electricityUnitUsed": "Units Used",
    "billing.noteRoomTotal": "Note: This bill is for the whole room, total.",
    "staff.manageUser": "Manage System User",
    "staff.manageStaff": "Manage Staff",
    "staff.manageStaffDesc": "Manage staff information and roles in the dormitory",
    "staff.addStaff": "Add New Staff",
    "staff.searchStaff": "Search Staff",
    "staff.searchStaffDesc": "Search staff by name, email, phone, or department",
    "staff.searchPlaceholder": "Search staff...",
    "staff.staffList": "Staff List",
    "staff.showCount": "Show items",
    "staff.name": "Staff Name",
    "staff.phone": "Phone",
    "staff.address": "Address",
    "staff.createdAt": "Created At",
    "staff.noData": "No staff found",
    "staff.noDataDesc": "No data in staff table",
    "staff.viewDetails": "View Details",
    "staff.edit": "Edit",
    "staff.delete": "Delete",
    "staff.confirmDelete": "Are you sure you want to delete?",
    "staff.loading": "Loading staff data...",
    "staff.detailTitle": "Staff Information",
    "staff.staffRole": "Staff",
    "staff.working": "Working",
    "staff.notWorking": "Not Working",
    "staff.email": "Email",
    "staff.position": "Position",
    "staff.department": "Department",
    "staff.updatedAt": "Last Updated",
    "staff.editTitle": "Edit Staff Information",
    "staff.addTitle": "Add New Staff",
    "staff.firstName": "First Name",
    "staff.lastName": "Last Name",
    "staff.houseNumber": "House Number",
    "staff.village": "Village",
    "staff.street": "Street",
    "staff.province": "Province",
    "staff.selectProvince": "Select province",
    "staff.district": "District",
    "staff.selectDistrict": "Select district",
    "staff.selectProvinceFirst": "Please select province first",
    "staff.subDistrict": "Sub-district",
    "staff.selectSubDistrict": "Select sub-district",
    "staff.selectDistrictFirst": "Please select district first",
    "staff.zipCode": "Zip Code",
    "staff.phoneOptional": "Phone (optional)",
    "staff.role": "Role",
    "common.saving": "Saving...",
    "common.update": "Update",
    "common.add": "Add",
    "tenants.manageUser": "Manage System User",
    "tenants.historyTitle": "Rental History",
    "tenants.historyDesc": "View details of former tenants who moved out",
    "tenants.confirmDelete": "Are you sure you want to delete?",
    "tenants.confirmDeleteChild": "Are you sure you want to delete rented child?",
    "tenants.loading": "Loading data...",
    "tenants.viewDetails": "View Details",
    // ...existing code...
  },

  //TH
  th: {
    "rooms.addDesc": "เพิ่มห้องใหม่ในหอพัก",
    "tenants.manageUser": "จัดการผู้ใช้ระบบ",
    "tenants.historyTitle": "ประวัติการเช่า",
    "tenants.historyDesc": "ดูรายละเอียดผู้เช่ารายเก่าที่ย้ายออกจากหอพัก",
    "tenants.searchTitle": "ค้นหาผู้เช่า",
    "tenants.searchDesc": "ค้นหาผู้เช่าด้วยชื่อ อีเมล เบอร์โทร หรือหมายเลขห้อง",
    "tenants.searchPlaceholder": "ค้นหาผู้เช่า...",
    "tenants.listTitle": "รายชื่อผู้เช่า",
    "tenants.showCount": "แสดงรายการ", 
    "tenants.name": "ผู้เช่า",
    "tenants.phone": "เบอร์โทร",
    "tenants.address": "ที่อยู่",
    "tenants.createdAt": "วันที่เพิ่ม",
    "tenants.noData": "ไม่มีข้อมูลผู้เช่า",
    "tenants.viewDetails": "ดูรายละเอียด",
    "tenants.viewContractImage": "ดูรูปภาพสัญญา",
    "tenants.confirmDelete": "คุณแน่ใจหรือไม่ที่จะลบ?",
    "tenants.confirmDeleteChild": "คุณแน่ใจหรือไม่ที่จะลบลูกเช่าของ?",
    "tenants.loading": "กำลังโหลดข้อมูล...",
    "staff.editTitle": "แก้ไขข้อมูลพนักงาน",
    "staff.addTitle": "เพิ่มพนักงานใหม่",
    "staff.firstName": "ชื่อ",
    "staff.lastName": "นามสกุล",
    "staff.houseNumber": "บ้านเลขที่",
    "staff.village": "หมู่ที่",
    "staff.street": "ถนน",
    "staff.province": "จังหวัด",
    "staff.selectProvince": "เลือกจังหวัด",
    "staff.district": "อำเภอ/เขต",
    "staff.selectDistrict": "เลือกอำเภอ",
    "staff.selectProvinceFirst": "กรุณาเลือกจังหวัดก่อน",
    "staff.subDistrict": "ตำบล/แขวง",
    "staff.selectSubDistrict": "เลือกตำบล",
    "staff.selectDistrictFirst": "กรุณาเลือกอำเภอก่อน",
    "staff.zipCode": "รหัสไปรษณีย์",
    "staff.phoneOptional": "เบอร์โทร (ไม่บังคับ)",
    "staff.role": "บทบาท",
    "staff.staffRole": "ผู้ช่วย (Staff)",
    "common.cancel": "ยกเลิก",
    "common.saving": "กำลังบันทึก...",
    "common.update": "อัปเดต",
    "common.add": "เพิ่ม",
    "staff.detailTitle": "ข้อมูลพนักงาน",
    "staff.working": "ทำงานอยู่",
    "staff.notWorking": "ไม่ได้ทำงาน",
    "staff.email": "อีเมล",
    "staff.phone": "เบอร์โทร",
    "staff.address": "ที่อยู่",
    "staff.position": "ตำแหน่ง",
    "staff.department": "แผนก",
    "staff.createdAt": "สร้างเมื่อ",
    "staff.updatedAt": "อัปเดตล่าสุด",
    "staff.manageUser": "จัดการผู้ใช้ระบบ",
    "staff.manageStaff": "จัดการพนักงาน",
    "staff.manageStaffDesc": "จัดการข้อมูลพนักงานและบทบาทในหอพัก",
    "staff.addStaff": "เพิ่มพนักงานใหม่",
    "staff.searchStaff": "ค้นหาพนักงาน",
    "staff.searchStaffDesc": "ค้นหาพนักงานตามชื่อ อีเมล เบอร์โทร หรือแผนก",
    "staff.searchPlaceholder": "ค้นหาพนักงาน...",
    "staff.staffList": "รายชื่อพนักงาน",
    "staff.showCount": "แสดงรายการ",
    "staff.name": "ชื่อพนักงาน",
    "staff.noData": "ไม่พบข้อมูลพนักงาน",
    "staff.noDataDesc": "ไม่มีข้อมูลในตารางพนักงาน",
    "staff.viewDetails": "ดูรายละเอียด",
    "staff.edit": "แก้ไข",
    "staff.delete": "ลบ",
    "staff.confirmDelete": "คุณแน่ใจหรือไม่ที่จะลบ {name}?",
    "staff.loading": "กำลังโหลดข้อมูลพนักงาน...",
    "billing.previousMeter": "เลขมิเตอร์เก่า",
    "billing.currentMeter": "เลขมิเตอร์ใหม่",
    "billing.meterError": "กรุณากรอกเลขมิเตอร์ใหม่ให้ถูกต้อง",
    "billing.electricityUnitUsed": "หน่วยที่ใช้",
    "billing.noteRoomTotal": "หมายเหตุ: บิลนี้สำหรับทั้งห้อง ",
    "billing.tenantName": "ชื่อผู้เช่า",
    "billing.paymentSuccess": "ชำระเงินสำเร็จ",
    "billing.paymentSuccessDesc": "การชำระเงินเสร็จสมบูรณ์",
    "billing.notPaid": "ยังไม่ได้ชำระ",
    "billing.detailTitle": "รายละเอียดบิล",
    "billing.receiptNumber": "เลขที่ใบเสร็จ",
    "billing.forRoom": "บิลสำหรับห้อง",
    "billing.printReceipt": "ปริ้นใบเสร็จ",
    "billing.tenantInfo": "ข้อมูลผู้เช่า",
    "billing.roomNumber": "หมายเลขห้อง",
    "billing.expenseDetail": "รายละเอียดค่าใช้จ่าย",
    "billing.forMonth": "ประจำเดือน {month}",
    "billing.roomRent": "ค่าห้อง",
    "billing.waterCost": "ค่าน้ำ",
    "billing.electricityCost": "ค่าไฟ",
    "billing.personUnit": "คน",
    "billing.electricityUnit": "หน่วย",
    "billing.baht": "บาท",
    "billing.total": "รวมทั้งสิ้น",
    "billing.paymentInfo": "ข้อมูลการชำระเงิน",
    "billing.dueDate": "วันครบกำหนดชำระ",
    "billing.paidDate": "วันที่ชำระ",
    "billing.status": "สถานะ",
    "billing.createdAt": "วันที่สร้างบิล",
    "billing.billingDate": "วันที่คิดค่าใช้จ่าย",
    "billing.calculateTitle": "คำนวณค่าใช้จ่าย (ตามห้อง)",
    "billing.calculateDesc": "คำนวณค่าห้อง + ค่าน้ำ  + ค่าไฟ )",
    "billing.createBill": "สร้างบิล",
    "billing.creating": "กำลังสร้าง...",
    "billing.listTitle": "รายการบิล",
    "billing.showCount": "แสดง",
    "billing.month": "เดือน",
    "billing.tenant": "ผู้เช่า",
    "billing.room": "ห้อง",
    "billing.actions": "การดำเนินการ",
    "billing.viewDetails": "ดูรายละเอียด",
    "billing.edit": "แก้ไข",
    "billing.markAsPaid": "ชำระแล้ว",
    "billing.pay": "ชำระเงิน",
    "billing.noData": "ไม่พบข้อมูลบิลที่ตรงกับเงื่อนไขการค้นหา",
    "billing.confirmMarkAsPaid": "คุณแน่ใจหรือไม่ว่าต้องการยืนยันการชำระเงิน?",
    "billing.cancel": "ยกเลิก",
    "billing.confirm": "ยืนยันการชำระเงิน",
    "billing.filtersTitle": "ค้นหาและกรอง",
    "billing.filtersDesc": "ค้นหาบิลตามชื่อผู้เช่าหรือหมายเลขห้อง และกรองตามเดือน/ปี",
    "billing.searchPlaceholder": "ค้นหาบิล...",
    "billing.statusFilter": "กรองตามสถานะ",
    "billing.status_all": "ทุกสถานะ",
    "billing.status_paid": "ชำระแล้ว",
    "billing.status_pending": "รอชำระ",
    "billing.status_overdue": "เกินกำหนด",
    "billing.title": "ระบบคิดเงิน",
    "billing.description": "จัดการการคิดค่าใช้จ่ายของหอพัก",
    "billing.export": "ส่งออก",
    "billing.calculate": "คำนวณค่าใช้จ่าย",
    "dashboard.overview": "ภาพรวมระบบจัดการหอพัก",
    "welcome.contact": "ติดต่อเรา",
    "welcome.phone": "โทร",
    "welcome.facebook": "เฟซบุ๊ก",
    "calendar.title": "ปฏิทิน",
    "calendar.subtitle": "จัดการกิจกรรมและประกาศของคุณ",
    "calendar.infoTitle": "ข้อมูลปฏิทิน",
    "calendar.infoDesc": "ดูและจัดการกิจกรรมบนปฏิทิน",
    "repairs.status_all": "ทุกสถานะ",
    "common.actions": "การดำเนินการ",
    "common.delete": "ลบ",
    "common.viewDetails": "ดูรายละเอียด",
    "common.edit": "แก้ไข",
    "repairs.markInProgress": "ทำเครื่องหมายเป็นกำลังดำเนินการ",
    "repairs.markImportant": "ทำเครื่องหมายเป็นสำคัญ",
    "repairs.markCompleted": "ทำเครื่องหมายเป็นเสร็จสิ้น",
    "repairs.markCancelled": "ทำเครื่องหมายเป็นยกเลิก",
    "repairs.createDescription": "สร้างคำขอซ่อมแซมใหม่สำหรับผู้เช่า",
    "repairs.title": "การซ่อมแซม",
    "repairs.subtitle": "จัดการคำขอซ่อมแซมและบำรุงรักษา",
    "repairs.searchPlaceholder": "ค้นหาการซ่อมแซม",
    "repairs.status_pending": "รอดำเนินการ",
    "repairs.status_in_progress": "กำลังดำเนินการ",
    "repairs.status_completed": "เสร็จสิ้น",
    "repairs.status_cancelled": "ยกเลิก",
    "Search by room number": "ค้นหาตามหมายเลขห้อง",

    "All Statuses": "ทุกสถานะ",
    "announcements.noAvailable": "ไม่มีประกาศสำหรับวันที่นี้",
    "announcements.contentPlaceholder": "กรุณากรอกเนื้อหาประกาศที่นี่",
    "announcements.markImportant": "ทำเครื่องหมายเป็นสำคัญ",
    "announcements.createDescription": "สร้างประกาศใหม่สำหรับผู้เช่า",
    "app.title": "บ้านพุทธชาติ",
    "nav.dashboard": "แดชบอร์ด",
    "nav.rooms": "ห้องพัก",
    "nav.tenantsold": "ประวัติผู้เช่า",
    "nav.tenants": "ผู้เช่า",
    "nav.staff": "พนักงาน",
    "nav.billing": "การเงิน",
    "nav.repairs": "แจ้งซ่อม",
    "nav.announcements": "ประกาศ",
    "nav.reports": "รายงาน",
    "nav.profile": "โปรไฟล์",
    "nav.settings": "ตั้งค่า",
    "auth.login": "เข้าสู่ระบบ",
    "auth.logout": "ออกจากระบบ",
    "auth.register": "ลงทะเบียน",
    "auth.email": "อีเมล",
    "auth.password": "รหัสผ่าน",
    "auth.confirmPassword": "ยืนยันรหัสผ่าน",
    "auth.role": "ตำแหน่ง",
    "auth.welcomeBack": "ยินดีต้อนรับกลับ",
    "auth.pleaseLogin": "กรุณาเข้าสู่ระบบเพื่อดำเนินการต่อ",
    "dashboard.welcome": "ยินดีต้อนรับสู่แดชบอร์ดของคุณ",
    "dashboard.summary": "นี่คือสรุปข้อมูลหอพักของคุณ",
    "dashboard.totalRooms": "จำนวนห้องทั้งหมด",
    "dashboard.occupiedRooms": "ห้องที่มีผู้เช่า",
    "dashboard.vacantRooms": "ห้องว่าง",
    "dashboard.pendingRepairs": "การซ่อมแซมที่รอดำเนินการ",
    "dashboard.monthlyRevenue": "รายได้ประจำเดือน",
    "dashboard.revenueTrend": "แนวโน้มรายได้ในช่วง 6 เดือนที่ผ่านมา",
    "dashboard.revenue": "รายได้",
    "dashboard.roomStatus": "สถานะห้องพัก",
    "dashboard.currentRoomOccupancy": "จำนวนผู้เข้าพักห้องปัจจุบัน",
    "dashboard.roomsOccupied": "ห้องที่มีผู้เข้าพัก",
    "dashboard.occupancy": "อัตราการเข้าพัก",
    "dashboard.Description": "แนวโน้มรายได้ในช่วง 6 เดือนที่ผ่านมา",
    "rooms.management": "จัดการห้องพัก",
    "rooms.allTypes": "ทุกประเภท",
    "rooms.number": "หมายเลขห้อง",
    "rooms.type": "ประเภทห้อง",
    "rooms.status": "สถานะ",
    "rooms.rent": "ค่าเช่ารายเดือน",
    "rooms.size": "ขนาดห้อง",
    "rooms.capacity": "ความจุ (คน)",
    "rooms.floor": "ชั้น",
    "rooms.add": "เพิ่มห้อง",
    "rooms.add_description": "เพิ่มห้องพักใหม่ภายในหอพัก",
    "Standard.Single": "ห้องเดี่ยว",
    "Standard.Double": "ห้องคู่",
    "satatus.occupied": "มีผู้เช่า",
    "satatus.vacant": "ห้องว่าง",
    "satatus.maintenance": "อยู่ระหว่างซ่อมแซม",
    "status.text": "สถานะห้อง",
    "rooms.edit": "แก้ไขห้อง",
    "rooms.delete": "ลบห้อง",
    "tenants.management": "จัดการผู้เช่า",
    "tenants.room": "ห้อง",
    "tenants.contactInfo": "ข้อมูลติดต่อ",
    "tenants.leaseStart": "วันเริ่มสัญญา",
    "tenants.leaseEnd": "วันสิ้นสุดสัญญา",
    "tenants.add": "เพิ่มผู้เช่า",
    "tenants.edit": "แก้ไขข้อมูลผู้เช่า",
    "tenants.delete": "ลบผู้เช่า",
    "repairs.management": "จัดการการซ่อมแซม",
    "repairs.room": "ห้อง",
    "repairs.description": "รายละเอียด",
    "repairs.status": "สถานะ",
    "repairs.date": "วันที่แจ้ง",
    "repairs.add": "เพิ่มการแจ้งซ่อม",
    "repairs.edit": "แก้ไขการซ่อม",
    "repairs.delete": "ลบการซ่อม",
    "repairs.viewDetails": "รายละเอียดการซ่อมแซม",
    "repairs.roomNumber": "ห้อง",
    "repairs.reportedDate": "วันที่แจ้งซ่อม",
    "repairs.completedDate": "วันที่ซ่อมเสร็จ",
    "repairs.status.pending": "รอดำเนินการ",
    "repairs.status.in_progress": "กำลังดำเนินการ",
    "repairs.status.completed": "เสร็จสิ้น",
    "repairs.status.cancelled": "ยกเลิก",
    "language.en": "English",
    "language.th": "ไทย",
    "theme.title": "ธีมและภาษา",
    "theme.description": "ปรับแต่งรูปลักษณ์และภาษาของระบบ",
    "theme.theme": "ธีม",
    "theme.light": "สว่าง",
    "theme.dark": "มืด",
    "theme.language": "ภาษา",
    "theme.thai": "ไทย",
    "theme.english": "อังกฤษ",
    "theme.lightTheme": "ธีมสว่าง",
    "theme.darkTheme": "ธีมมืด",
    "roomer.text1": "สถานะห้องพัก",
    "roomer.text2": "จำนวนผู้เข้าพักห้องปัจจุบัน",
    "footer.rights": "สงวนลิขสิทธิ์",
    "welcome.title": "ยินดีต้อนรับสู่หอพักบ้านพุทธชาติ นครปฐม",
    "welcome.subtitle": "พื้นที่พักอาศัยทันสมัยสำหรับนักศึกษา",
    "welcome.login": "เข้าสู่ระบบเพื่อเข้าถึงบัญชีของคุณ",
    "welcome.explore": "ดูห้องพักที่มี",
    "welcome.features": "สิ่งอำนวยความสะดวก",
    "welcome.location": "ทำเลดี",
    "welcome.security": "ระบบรักษาความปลอดภัย 24 ชั่วโมง",
    "welcome.amenities": "สิ่งอำนวยความสะดวกทันสมัย",
    "profile.title": "โปรไฟล์ส่วนตัว",
    "profile.manage": "จัดการข้อมูลส่วนตัวของคุณ",
    "profile.firstName": "ชื่อ",
    "profile.lastName": "นามสกุล",
    "profile.email": "อีเมล",
    "profile.phone": "เบอร์โทรศัพท์",
    "profile.address": "ที่อยู่",
    "profile.enterPhone": "กรุณาใส่เบอร์โทรศัพท์",
    "profile.enterAddress": "กรุณาใส่ที่อยู่",
    "profile.save": "บันทึกการเปลี่ยนแปลง",
    "profile.saving": "กำลังบันทึก...",
    "profile.saveSuccess": "บันทึกโปรไฟล์สำเร็จ!",
    "profile.saveError": "ไม่สามารถบันทึกโปรไฟล์ได้",
    "profile.userNotFound": "ไม่พบข้อมูลผู้ใช้",
    "profile.genericError": "เกิดข้อผิดพลาดในการบันทึกข้อมูล",
    "system.title": "ตั้งค่าระบบ",
    "system.description": "การตั้งค่าระบบและการบำรุงรักษา (เฉพาะผู้ดูแลระบบ)",
    "system.info": "ข้อมูลระบบ",
    "system.totalRooms": "ห้องทั้งหมด",
    "system.occupiedRooms": "ห้องที่เช่าแล้ว",
    "system.totalTenants": "ผู้เช่าทั้งหมด",
    "system.pendingRepairs": "งานซ่อมรอดำเนินการ",
    "system.configTitle": "การตั้งค่าระบบ",
    "system.waterRate": "อัตราค่าน้ำ (คน/บาท)",
    "system.electricityRate": "อัตราค่าไฟ (บาท/หน่วย)",
    "system.lateFee": "ค่าปรับชำระล่าช้า (%)",
    "system.depositRate": "ค่าเช่ารายเดือน",
    "system.floor": "ชั้นตึก",
    "system.save": "บันทึกการตั้งค่า",
    "system.saving": "กำลังบันทึก...",
    "system.maintenance": "การบำรุงรักษาระบบ",
    "system.backup": "สำรองข้อมูล",
    "system.backuping": "กำลังสำรอง...",
    "system.clearCache": "ล้าง Cache",
    "system.check": "ตรวจสอบระบบ",
    "system.status": "สถานะระบบ",
    "system.database": "ฐานข้อมูล",
    "system.connection": "การเชื่อมต่อ",
    "system.storage": "พื้นที่จัดเก็บข้อมูล",
    "system.normal": "ปกติ",
    "system.used": "ใช้ไป 65%",
    "reports.title": "รายงาน",
    "reports.subtitle": "ดูและวิเคราะห์ข้อมูลหอพัก",
    "reports.exportPdf": "ส่งออก PDF",
    "reports.exporting": "กำลังส่งออก...",
    "reports.options": "ตัวเลือกการรายงาน",
    "reports.selectType": "เลือกประเภทของรายงาน",
    "reports.type": "ประเภทของรายงาน",
    "reports.selectTypePlaceholder": "เลือกประเภทของรายงาน",
    "reports.selectTypeDesc": "เลือกประเภทของรายงานเพื่อดูข้อมูล",
    "reports.occupancyTitle": "แนวโน้มการเข้าพัก",
    "reports.occupancyDesc": "อัตราการเข้าพักหอพักรายเดือน",
    "reports.revenueTitle": "วิเคราะห์รายได้",
    "reports.revenueDesc": "สรุปรายรับรายเดือน",
    "reports.roomTypeTitle": "สัดส่วนประเภทห้อง",
    "reports.roomTypeDesc": "สัดส่วนของแต่ละประเภทห้อง",
    "reports.repairTitle": "วิเคราะห์การแจ้งซ่อม",
    "reports.repairDesc": "ประเภทของการแจ้งซ่อมที่ได้รับ",
    "reports.eventTitle": "การเข้าร่วมกิจกรรม",
    "reports.eventDesc": "สถิติการเข้าร่วมกิจกรรมของหอพัก",
    "loading": "กำลังโหลด...",
    "tenants.managementDesc": "จัดการข้อมูลผู้เช่าและห้องที่เช่าในหอพัก",
    "tenants.main": "ผู้เช่าหลัก",
    "tenants.child": "ผู้เช่ารอง",
    "tenants.notRented": "ยังไม่มีผู้เช่า",
    "tenants.addChild": "เพิ่มผู้เช่ารอง",
    "tenants.addContractImage": "เพิ่มรูปสัญญาเช่า",
    "tenants.deleteChild": "ลบผู้เช่ารอง",
    "tenants.deleteConfirm": "คุณแน่ใจหรือไม่ว่าต้องการลบ ?",
    "tenants.deleteChildConfirm": "คุณแน่ใจหรือไม่ว่าต้องการลบผู้เช่ารองของ ?",
    "tenants.deleteSuccess": "ลบผู้เช่าสำเร็จ",
    "tenants.formDesc": "กรุณากรอกข้อมูลผู้เช่าทั้งหมด",
    "tenants.firstNameRequired": "กรุณากรอกชื่อ",
    "tenants.lastNameRequired": "กรุณากรอกนามสกุล",
    "tenants.emailInvalid": "อีเมลไม่ถูกต้อง",
    "tenants.phoneRequired": "กรุณากรอกเบอร์โทรศัพท์",
    "tenants.houseNumberRequired": "กรุณากรอกบ้านเลขที่",
    "tenants.villageRequired": "กรุณากรอกหมู่บ้าน",
    "tenants.subDistrictRequired": "กรุณากรอกตำบล",
    "tenants.districtRequired": "กรุณากรอกอำเภอ",
    "tenants.provinceRequired": "กรุณากรอกจังหวัด",
    "dashboard.totalRevenue": "รายได้รวม",
    "dashboard.Revenue": "รายได้",
    "tenants.tenantInfo": "ข้อมูลผู้เช่า",
    "tenants.residents": "ผู้พักอาศัย",
    "tenants.selectDistrictFirst": "กรุณาเลือกอำเภอก่อน",
    "tenants.saveTenant": "บันทึกผู้เช่า",
    "tenants.saveResident": "บันทึกผู้พักอาศัย",
    "tenants.checkIn": "เช็คอิน",
    "tenants.lastUpdated": "อัปเดตล่าสุด",
    "tenants.floor": "ชั้น",
    "tenants.emergencyContact": "ข้อมูลติดต่อฉุกเฉิน",
    "tenants.roommates": "เพื่อนร่วมห้อง",
    "tenants.viewContractFile": "ดูไฟล์สัญญาเช่า",
    "tenants.showContractFileDesc": "แสดงไฟล์สัญญาเช่า",
    "tenants.loadingFile": "กำลังโหลดไฟล์...",
    "tenants.fileNotFound": "ไม่พบไฟล์สัญญาเช่า",
    "tenants.pdfContractTitle": "สัญญาเช่า PDF",
    "tenants.contractImageAlt": "สัญญาเช่า",
    "profile.tenantOnlyEdit": "เฉพาะผู้เช่าสามารถแก้ไขโปรไฟล์ของตนเองได้",
    "announcements.calendar": "ปฏิทิน",
    "announcements.add": "เพิ่มประกาศ",
    "announcements.edit": "แก้ไขประกาศ",
    "announcements.delete": "ลบประกาศ",
    "announcements.title": "หัวข้อ",
    "announcements.description": "รายละเอียด",
    "announcements.date": "วันที่",
    "announcements.time": "เวลา",
    "announcements.addSuccess": "เพิ่มประกาศสำเร็จ",
    "announcements.editSuccess": "แก้ไขประกาศสำเร็จ",
    "announcements.deleteSuccess": "ลบประกาศสำเร็จ",
    "announcements.deleteConfirm": "คุณแน่ใจหรือไม่ว่าต้องการลบประกาศนี้?",
    "announcements.deleteError": "ไม่สามารถลบประกาศได้ กรุณาลองใหม่อีกครั้ง",
    "announcements.addError": "ไม่สามารถเพิ่มประกาศได้ กรุณาลองใหม่อีกครั้ง",
    "announcements.editError": "ไม่สามารถแก้ไขประกาศได้ กรุณาลองใหม่อีกครั้ง",
    "announcements.noAnnouncements": "ไม่มีประกาศใดๆ",
    "announcements.noData": "ไม่มีข้อมูลประกาศ",
    "announcements.viewDetails": "ดูรายละเอียด",
    "announcements.editDetails": "แก้ไขรายละเอียดประกาศ",
    "announcements.deleteDetails": "ลบรายละเอียดประกาศ",
    "announcements.titleRequired": "หัวข้อประกาศจำเป็นต้องกรอก",
    "announcements.descriptionRequired": "รายละเอียดประกาศจำเป็นต้องกรอก",
    "announcements.dateRequired": "วันที่ประกาศจำเป็นต้องกรอก",
    "announcements.timeRequired": "เวลาประกาศจำเป็นต้องกรอก",
    "announcements.titlePlaceholder": "กรอกหัวข้อประกาศ",
    "announcements.descriptionPlaceholder": "กรอกรายละเอียดประกาศ",
    "announcements.datePlaceholder": "เลือกวันที่ประกาศ",
    "announcements.timePlaceholder": "เลือกเวลาประกาศ",
    "announcements.addAnnouncement": "เพิ่มประกาศ",
    "announcements.editAnnouncement": "แก้ไขประกาศ",
    "announcements.deleteAnnouncement": "ลบประกาศ",
    "announcements.viewAnnouncement": "ดูประกาศ",
    "announcements.announcementDetails": "รายละเอียดประกาศ",
    "announcements.announcementList": "รายการประกาศ",
    "announcements.recent": "ประกาศล่าสุด",
    "days.Sun": "อาทิตย์",
    "days.Mon": "จันทร์",
    "days.Tue": "อังคาร",
    "days.Wed": "พุธ",
    "days.Thu": "พฤหัสบดี",
    "days.Fri": "ศุกร์",
    "days.Sat": "เสาร์",
    "months.January": "มกราคม",
    "months.February": "กุมภาพันธ์",
    "months.March": "มีนาคม",
    "months.April": "เมษายน",
    "months.May": "พฤษภาคม",
    "months.June": "มิถุนายน",
    "months.July": "กรกฎาคม",
    "months.August": "สิงหาคม",
    "months.September": "กันยายน",
    "months.October": "ตุลาคม",
    "months.November": "พฤศจิกายน",
    "months.December": "ธันวาคม",
    "announcements.calendarView": "มุมมองปฏิทิน",
    "announcements.listView": "มุมมองรายการ",
    "announcements.view": "ดูประกาศ",
    "announcements.viewDesc": "ดูรายละเอียดของประกาศนี้",
    "announcements.addDesc": "เพิ่มประกาศใหม่สำหรับผู้เช่า",
    "announcements.editDesc": "แก้ไขประกาศที่เลือก",
    "announcements.deleteDesc": "ลบประกาศที่เลือก",
    "announcements.loading": "กำลังโหลดประกาศ...",
    "announcements.loadingError": "ไม่สามารถโหลดประกาศได้ กรุณาลองใหม่อีกครั้ง",
    "announcements.viewDetailsDesc": "ดูรายละเอียดของประกาศนี้",
    "announcements.editDetailsDesc": "แก้ไขรายละเอียดของประกาศนี้",
    "announcements.deleteDetailsDesc": "ลบประกาศนี้",
    "announcements.addAnnouncementDesc": "เพิ่มประกาศใหม่สำหรับผู้เช่า",
    "announcements.editAnnouncementDesc": "แก้ไขประกาศที่เลือก",
    "announcements.deleteAnnouncementDesc": "ลบประกาศที่เลือก",
    "announcements.viewAnnouncementDesc": "ดูรายละเอียดของประกาศนี้",
    "announcements.announcementDetailsDesc": "รายละเอียดของประกาศ",
    "announcements.forDate": "สำหรับวันที่",
    "announcements.forTime": "สำหรับเวลา",
    "announcements.noForDate": "ไม่พบประกาศใดๆ",
    "rooms.detailsTitle": "รายละเอียดห้องพัก",
    "rooms.detailsDesc": "ข้อมูลทั้งหมดเกี่ยวกับห้องพักนี้",
    "rooms.person": "คน",
    "rooms.currentTenants": "ผู้เช่าปัจจุบัน",
    "rooms.mainTenant": "ผู้เช่าหลัก",
    "rooms.subTenant": "ผู้เช่ารอง",
    "rooms.noCurrentTenant": "ไม่มีผู้เช่าปัจจุบัน",
    "rooms.loadingTenants": "กำลังโหลดข้อมูลผู้เช่า...",
    "manageSystemUsers": "จัดการผู้ใช้ระบบ",
    "Actions.text": "การดำเนินการ",
    "tenants.addChildDesc": "เพิ่มผู้เช่ารองในห้องนี้",
    "tenants.deleteChildDesc": "ลบผู้เช่ารองในห้องนี้",
    "tenants.viewContractImageDesc": "ดูรูปภาพสัญญาเช่า",
    "tenants.addContractImageDesc": "เพิ่มรูปภาพสัญญาเช่า",
    "tenants.deleteChildConfirmDesc": "คุณแน่ใจหรือไม่ว่าต้องการลบผู้เช่ารองของ {name}?",
    "tenants.deleteChildSuccess": "ลบผู้เช่ารองสำเร็จ",
    "tenants.deleteChildError": "ไม่สามารถลบผู้เช่ารองได้ กรุณาลองใหม่อีกครั้ง",
    "view_details": "ดูรายละเอียด",
    "edit": "แก้ไข",
  },
};

export function LanguageProvider({
  children,
  defaultLanguage = "en",
}: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>(
    () => (localStorage.getItem("language") as Language) || defaultLanguage
  );

  useEffect(() => {
    document.documentElement.setAttribute("lang", language);
    localStorage.setItem("language", language);
  }, [language]);

  // Translation function
  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const value = {
    language,
    setLanguage: (language: Language) => {
      setLanguage(language);
    },
    t,
  };

  return (
    <LanguageProviderContext.Provider value={value}>
      {children}
    </LanguageProviderContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageProviderContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
export function useTranslation() {
  const { t } = useLanguage();
  return t;
}